language: node_js
node_js:
  - "12"

script:
  - npm run export

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: __sapper__/export
  target_branch: gh-pages
  fqdn: nick.winans.codes
  on:
    branch: dev
